### ISSUE TITLE
Add dynamic route error (FreePBX 15.0.16.81, PHP 7.3)

### ISSUE THREAD

**Issue by varlog11** [johnfawcett/dynroute#14]
Hi!

When I try to add a route, I get the error

Whoops \ Exception \ ErrorException (E_WARNING)
Use of undefined constant action - assumed 'action' (this will throw an Error in a future version of PHP)

Whoops\Exception\ErrorException 
/var/www/pbx/admin/modules/dynroute/views/form.php8
3
Whoops\Run handleError
/var/www/pbx/admin/modules/dynroute/views/form.php8
2
 include
/var/www/pbx/admin/libraries/view.functions.php158
1
 load_view
/var/www/pbx/admin/modules/dynroute/page.dynroute.php72
0
 include
/var/www/pbx/admin/config.php646

**Comment by johnfawcett** [comment]
Hi
looks like a long standing bug that however did not affect the functioning of the module until php 7 stricter syntax checking.

Do you have the chance to apply the following patch and verify?

--- form.php.orig	2020-12-16 14:25:19.249737724 +0100
+++ form.php	2020-12-16 13:44:49.718742285 +0100
@@ -5,7 +5,7 @@
 // Freepbx IVR module
 
 extract($request, EXTR_SKIP);
-if(action == 'add'){
+if($action == 'add'){
 	$heading = _("Add Dynamic Route");
 	$deet = array('id', 'name', 'description', 'sourcetype',
 				'mysql_host','mysql_dbname','mysql_query','mysql_username','mysql_password',

**Comment by varlog11** [comment]
Yes, it helped. I will test. Thank you!

**Comment by varlog11** [comment]
Now, when trying to save, it gives an error

Exception
Array ( [name] => test [description] => 1111 [sourcetype] => astvar [mysql_host] => [mysql_dbname] => [mysql_query] => [mysql_username] => [mysql_password] => [odbc_func] => [odbc_query] => [url_query] => [agi_query] => [agi_var_name_res] => [astvar_query] => ggg [enable_dtmf_input] => [max_digits] => 0 [timeout] => 5 [announcement_id] => None [chan_var_name] => www [chan_var_name_res] => eeee [validation_regex] => [max_retries] => 0 [invalid_retry_rec_id] => Нет [invalid_rec_id] => None [invalid_dest] => app-blackhole,hangup,1 [default_dest] => app-blackhole,hangup,1 ) SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'None' for column `asterisk`.`dynroute`.`announcement_id` at row 1::

Exception 
/var/www/pbx/admin/libraries/utility.functions.php123
3
 die_freepbx
/var/www/pbx/admin/modules/dynroute/functions.inc.php296
2
 dynroute_save_details
/var/www/pbx/admin/modules/dynroute/functions.inc.php252
1
 dynroute_configprocess
/var/www/pbx/admin/libraries/components.class.php469
0
component processconfigpage
/var/www/pbx/admin/config.php449

**Comment by johnfawcett** [comment]
Which version of dynamic routes are you using?

**Comment by varlog11** [comment]
<rawname>dynroute</rawname>
	<repo>local</repo>
	<name>Dynamic Routes</name>
	<version>15.0.0</version>
	<publisher>John Fawcett</publisher>
	<info>https://www.voipsupport.it/</info>
	<license>GPLv3+</license>
	<licenselink>http://www.gnu.org/licenses/gpl-3.0.txt</licenselink>
	<category>Applications</category>

**Comment by johnfawcett** [comment]
I can't reproduce that, but I don't have php 7 installed. What was your starting point for the install, the Freepbx distro or an install from tarball, on which operating system and which database and version?

**Comment by varlog11** [comment]
I am using Debian 10. Installed from the tarball.
Server version: 10.3.27-MariaDB-0+deb10u1 Debian 10

**Comment by johnfawcett** [comment]
I don't have access to a Freepbx environment with php 7 installed. Are other things like saving IVR working? 

Would you be able to help with more debugging of the problem? The error message indicates two issues, neither of which are an issue on my environment. First one is "Invalid datetime format". In the table asterisk.dynroute there is no datetime column. 

Second one is "Incorrect integer value: 'None' for column asterisk.dynroute.announcement_id". The value "None" should not arrive in the query because before the dynroute_save_entries() function is called in functions.inc.php, a check is done and if the announcement_id is "None" then the value is set to 0:

 $vars['announcement_id'] = empty($vars['announcement_id']) || $vars['announcement_id'] == 'None' ? '0' : $vars['announcement_id'];

John

**Comment by varlog11** [comment]
I have installed FreePBX 15.0.17.5 on Debian 10 so you can test.
I sent to your mail the credentials of the test server.

**Comment by johnfawcett** [comment]
Thanks for that. I've successfully added a dynamic route on your test server. I don't see the issue. Could you tryit?

**Comment by varlog11** [comment]
I tested. No error occurs when using the English interface.
The problem appears when I use Russian.

Array ( [name] => dddd [description] => ssss [sourcetype] => none [mysql_host] => [mysql_dbname] => [mysql_query] => [mysql_username] => [mysql_password] => [odbc_func] => [odbc_query] => [url_query] => [agi_query] => [agi_var_name_res] => [astvar_query] => [enable_dtmf_input] => [max_digits] => 0 [timeout] => 5 [announcement_id] => Нет [chan_var_name] => [chan_var_name_res] => [validation_regex] => [max_retries] => 0 [invalid_retry_rec_id] => Нет [invalid_rec_id] => Нет [invalid_dest] => [default_dest] => ) SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'Нет' for column `asterisk`.`dynroute`.`announcement_id` at row 1::

**Comment by johnfawcett** [comment]
Hi
I can see that the issue was the code patch done to resolve a previous issue introduced with an updated Freepbx version: 

https://github.com/johnfawcett/dynroute/issues/13

The patch is not general enough and works only for English. With "Нет" value being returned from the Add Dynamic Route in Russian for three fields the patch is ineffective and passes those values directy through to SQL instead of sanitizing them to 0.

I have made a trial patch directly on your test server. I can verify that it works now for saving Dynamic Routes with Russian GUI. A further non regression test will be needed to ensure it correctly picks up annoucements, but I can do that on my own installation. Let me know if you find any further issues.

Once the fix is tested for regressions, I'll release it officially.

thanks again for your help.

**Comment by varlog11** [comment]
Today I will test.

Thanks for help!

**Comment by johnfawcett** [comment]
I have commited the final version of the fix here. This is the repository I'm now using to push changes to the freepbx contributed modules repository.
https://github.com/johnfawcett/freepbx-dynroute/blob/master/functions.inc.php
