### ISSUE TITLE
Need a timeout setting for any given dynamic route, that if it takes longer than that it uses the default destination.

### ISSUE THREAD

**Issue by xekon** [johnfawcett/dynroute#17]
Need a timeout setting for any given dynamic route, that if it takes longer than that it uses the default destination.

The reason being is that if your using a remote data source for your mysql/odbc query and that remote data source goes offline, it sometimes causes issues where dynamic routes just hangs, and the phones never end up ringing,
 I have watched the `asterisk -rvvvv` and can confirm this happens on multiple systems we are using.

I am not talking about the DTMF timeout, we have DTMF completely disabled in the dynamic route, I am talking about needing a timeout for the dynamic route itself.

The timeout values that I have defined directly in the odbc settings appear to work if the mysql container is offline at the remote location, but if the remote locations entire network goes offline including the router, then dynamic routes just hangs when it gets to the odbc query in dynamic routes.

originally worked off this: https://www.voipsupport.it/wiki/index.php/How_to_set_up_an_Asterisk_ODBC_data_source_on_Linux
and this was useful as well: https://mariadb.com/kb/en/about-mariadb-connector-odbc/

also some discussion here: https://www.reddit.com/r/freepbx/comments/qspa5i/dynamic_routes_module_needs_a_route_timeout/

I have configured timeout values in our `/etc/odbc.ini`:
```
[remoteserver]
Description=MySQL connection to remoteserver database
Trace=Off
TraceFile=stderr
Driver=MySQL
SERVER=remoteserver.example.com
PORT=3306
DATABASE=contacts
SSLVERIFY=1
CONN_TIMEOUT=1
readtimeout=1
```

I also have the timeouts configured in `/etc/asterisk/res_odbc_custom.conf`:
```
[remoteserver]
enabled=>yes
dsn=>remoteserver
username=>freepbx
password=>LongExamplePassword
pooling=>no
limit=>1
pre-connect=>yes
connect_timeout=>1
```

and for completeness sake the function in `/etc/asterisk/func_odbc.conf`:
(I was thinking that maybe there is a way to add a timeout to this function instead of to dynamic routes module?)
```
[remoteserver]
dsn=remoteserver
readsql=${ARG1}
```

**Comment by johnfawcett** [comment]
Hi
It is worth explaining the following point before answering. Dynamic Route module is a configuration GUI for Asterisk. The output of the configurations done in the GUI is Asterisk dial plan syntax written to the file /etc/asterisk/extensions_additional.conf. In particular Dynamic Route module writes sections in that file that begin with [dynroute-n] where n is a number.

If the underlying Asterisk functionality provides a timeout parameter Dynamic Routes can be modified to use it, but I don't see any such parameter and I suspect that Asterisk relies on the odbc configuration file timeouts you have already configured. I could suggest to open an enhancement request to Asterisk, but in this case I think it would be more appropriate to debug the issue on odbc (i.e. why isn't the odbc timeout parameter respected when the site goes off line). That should be done independently of Asterisk using the odbc query tool. If the odbc layer IS working correctly then a bug request should be filed with Asterisk as to why the query hangs If it turns out that something should be adjusted in the dial plan syntax that Dynamic Route generates in order to configure the timeout I'd be happy to fix it or enhance it.

Thanks for using Dynamic Route.

**Comment by xekon** [comment]
Thanks @johnfawcett would this function work for limiting the dynamic routes that use mysql/odbc

`https://www.asteriskguru.com/tutorials/timeoutresponse_function.html`

I am going to try editing the /etc/asterisk/extensions_additional.conf file and see what happens.

**Comment by johnfawcett** [comment]
As far as I know the Asterisk TIMEOUT function does not affect Mysql or ODBC calls. Let me know if you find differently and I would be happy to consider modifications to Dynamic Route.

**Comment by xekon** [comment]
you are correct that the timeout function does not help, I tested it:

`nano /etc/asterisk/extensions_additional.conf`

```
[dynroute-5] ; 2.CheckMySQLBlacklist
include => dynroute-5-custom
exten => s,1,Set(TIMEOUT(response)=3)
exten => s,2,Set(dynroute=${ODBC_remoteserver("SELECT COUNT(*) FROM (SELECT phone,name FROM blacklist WHERE (name LIKE '${CALLERID(name)}' OR phone LIKE '${CALLERID(num)}') LIMIT 1) AS myvar")})
```

`sudo reboot`

It did not, but if I find a solution I will post back here.
