### ISSUE TITLE
Won't Install on FreePBX 14

### ISSUE THREAD

**Issue by FreeSoftwareServers** [johnfawcett/dynroute#4]
Hey John, we spoke via E-Mail regarding installing this app on FreePBX 14/SNG7 (The new FreePBX Distro). I'm going to use this as a place to put my notes on installing this software on FreePBX 14 as this is the only aspect holding us back at my company from upgrading.

**Comment by FreeSoftwareServers** [comment]
![image](https://cloud.githubusercontent.com/assets/16218200/23828956/6f3deed8-06b0-11e7-9262-0cec32a72b8a.png)

**Comment by FreeSoftwareServers** [comment]
[root@freepbx dynroute]# php Dynroute.class.php
PHP Fatal error:  Class 'FreePBX_Helpers' not found in /var/www/html/admin/modules/dynroute/Dynroute.class.php on line 7

**Comment by FreeSoftwareServers** [comment]
Just FYI, Im grasping here a bit :P, slightly above my knowledge level. But I uncommented the \ in the PDO line on line 76 like so : 

` $results = $sth->fetchAll(PDO::FETCH_ASSOC);`
 
and got the following error:


`Class 'FreePBX\modules\PDO' not found`

**Comment by FreeSoftwareServers** [comment]
Hazzarr! So If I uncomment this entire "try" section, it installs. So this is clearly the problem.

```
//              try{
//                      $sql = "SELECT INDEX_NAME FROM INFORMATION_SCHEMA.STATISTICS WHERE "
//                              ."`TABLE_CATALOG` = 'def' AND `TABLE_SCHEMA` = DATABASE() AND "
//                              ."`TABLE_NAME` = '$table' AND `INDEX_NAME` = 'PRIMARY' ";
//                      $sth = $this->db->query($sql);
//                      $results = $sth->fetchAll(PDO::FETCH_ASSOC);
//                      if (empty($results)) {
//                              $sql = "ALTER TABLE $table
//                                      ADD PRIMARY KEY (`dynroute_id`,`selection`);";
//                              $sth = $this->db->prepare($sql);
//                              $sth->execute();
//                      }
//              } catch(PDOException $e) {
//                      return $e->getMessage();
//              }
```
![image](https://cloud.githubusercontent.com/assets/16218200/23829163/a5500a40-06b7-11e7-9f2c-56f283c3d0d0.png)

![image](https://cloud.githubusercontent.com/assets/16218200/23829165/bfd02b16-06b7-11e7-8a7d-d4e1f591882c.png)

Running the command in mysql workbench seems to work as well, so it does seem like a PDO error possibly.

![image](https://cloud.githubusercontent.com/assets/16218200/23829167/e8c562ac-06b7-11e7-928f-69f2f7225d2f.png)

**Comment by FreeSoftwareServers** [comment]
And this is where I leave it for the professionals. I'm going to run this by my co-workers who are PHP Programmers by trade, but also, you made the software :P, I think I helped diagnose the issue and hopefully move things closer to releasing a V14 Module. Based on the try statement returning successfully in MySQL, I feel like I can just comment this out and be fine, but it would be great to hear that from you!

**Comment by tm1000** [comment]
Feel free to ask on the FreePBX forums this question in the future as you probably would have saved a bit of time and headache. 

The problem is on adding a primary key to dynroute_id and selection because selection is VARCHAR(255). Lowering the number to 190 will probably work because 190 * 4 = 760. Which is lower than the error at 767

**Comment by johnfawcett** [comment]
It's a limitation for Innodb tables when innodb_large_prefix is disabled (the non default value). This problem probably has not come up before because in the past the character set was a non unicode one. Now with utf8, there will be 3 bytes needed per character + some additional bytes. Even on utf8 installations you may not see the issue if not using innodb storage engine or if you have the default unnodb_large_prefix setting.

https://dev.mysql.com/doc/refman/5.7/en/innodb-restrictions.html

For whoever is having this issue and does not want to change the innodb_large_prefix, it is worth reducing the varchar length as suggested by Andrew Nagy.

**Comment by xrobau** [comment]
Pull request by @tm1000 signed off by @xrobau

**Comment by xrobau** [comment]
Oh, and looking at the code, if you want to target 14, you can actually offload all the database table definition to the framework - [here's the specific documentation](http://wiki.freepbx.org/display/FOP/module.xml#module.xml-Database\(Framework14+\)) which also is part of our path forward of removing our reliance on MySQL.

If you have any further questions, please feel free to ask questions in #freepbx or #freepbx-dev on Freenode!

**Comment by johnfawcett** [comment]
Just a further update. The char set used is not utf8mb3 but utf8mb4 so as Andrew Nagy mentioned you need 4 bytes per character stored. I have merged the fix provided.
