### ISSUE TITLE
Multiple matches

### ISSUE THREAD

**Issue by vespino** [johnfawcett/dynroute#8]
First of all: live this module!

Second: I was wondering if it's possible to match for multiple values without having to duplicate the "Dynamic Route Entries". Let me explain: I use the module for presence detection. I have it connected to my wireless accesspoint which returned a value corresponding to how many people are home (1 just me, 2 just my wife, 3 we are both home). In case of 1 or 3 my business and private line need to ring, in case of 2 only the private line has to ring.

I could easily copy the "Dynamic Route Entries" and insert 1 entry for option 1 and 1 entry for option 3, but I'm lazy :) For my private line that would mean 3 entries.

Do you get what I mean?

Maybe a match value like 1,2,3 ?

**Comment by johnfawcett** [comment]
As it stands you can match only a single value. This could become an enhancement but there would need to be a separator character which cannot appear in any result and the choice of that could break backward compatibility The specific use case is not 100% clear to me. Is there a separate inbound route for business and private?

**Comment by vespino** [comment]
I have 2 inbound routes, business and private. I call a PHP script for the result.

**Comment by johnfawcett** [comment]
I confirm that the best way of doing this is to use multiple entries, you will need 1 entry for each possible value returned by the php script. Only way to avoid this is to use the default destination which is used when there is no match. So you could have only 1 entry which is for return value 2 and a default destination that takes care of any value different to 2 (i.e. values 1 and 3). Another alternative would be to switch the logic to the php script so that it returns 1 for routing to business and private and 2 for routing only to private.
